param([Parameter(Mandatory=$true)][string]$RepoRoot)
$ErrorActionPreference="Stop"
Set-StrictMode -Version Latest

function Die([string]$m){ throw $m }
function Write-Utf8NoBomLf([string]$Path,[string]$Text){
  $dir = Split-Path -Parent $Path
  if ($dir -and -not (Test-Path -LiteralPath $dir -PathType Container)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  $t = $Text.Replace("`r`n","`n").Replace("`r","`n")
  if (-not $t.EndsWith("`n")) { $t += "`n" }
  $enc = New-Object System.Text.UTF8Encoding($false)
  [System.IO.File]::WriteAllText($Path,$t,$enc)
}
function Parse-GateFile([string]$Path){
  if (-not (Test-Path -LiteralPath $Path -PathType Leaf)) { Die ("PARSEGATE_MISSING: " + $Path) }
  $enc = New-Object System.Text.UTF8Encoding($false)
  $txt = [System.IO.File]::ReadAllText($Path,$enc)
  [void][ScriptBlock]::Create($txt)
}

$RepoRoot = $RepoRoot.TrimEnd("\")
$LibPath = Join-Path $RepoRoot "scripts\_lib_neverlost_v1.ps1"
if (-not (Test-Path -LiteralPath $LibPath -PathType Leaf)) { Die ("MISSING_LIB: " + $LibPath) }
$bak = $LibPath + ".bak_" + (Get-Date -Format "yyyyMMdd_HHmmss")
Copy-Item -LiteralPath $LibPath -Destination $bak -Force

$New = New-Object System.Collections.Generic.List[string]
[void]$New.Add('$ErrorActionPreference="Stop"')
[void]$New.Add('Set-StrictMode -Version Latest')
[void]$New.Add('')
[void]$New.Add('function NL_Die([string]$m){ throw $m }')
[void]$New.Add('function NL_WriteUtf8NoBomLf([string]$Path,[string]$Text){')
[void]$New.Add('  $dir = Split-Path -Parent $Path')
[void]$New.Add('  if ($dir -and -not (Test-Path -LiteralPath $dir -PathType Container)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }')
[void]$New.Add('  $t = $Text.Replace("`r`n","`n").Replace("`r","`n")')
[void]$New.Add('  if (-not $t.EndsWith("`n")) { $t += "`n" }')
[void]$New.Add('  $enc = New-Object System.Text.UTF8Encoding($false)')
[void]$New.Add('  [System.IO.File]::WriteAllText($Path,$t,$enc)')
[void]$New.Add('}')
[void]$New.Add('function NL_ReadUtf8([string]$Path){ if(-not (Test-Path -LiteralPath $Path -PathType Leaf)){ return $null } $enc=New-Object System.Text.UTF8Encoding($false); [System.IO.File]::ReadAllText($Path,$enc) }')
[void]$New.Add('function NL_Sha256HexBytes([byte[]]$b){ if($null -eq $b){$b=@()} $sha=[System.Security.Cryptography.SHA256]::Create(); try{$h=$sha.ComputeHash([byte[]]$b)} finally{$sha.Dispose()} $sb=New-Object System.Text.StringBuilder; foreach($x in $h){[void]$sb.Append($x.ToString("x2"))}; $sb.ToString() }')
[void]$New.Add('')
[void]$New.Add('function NL_EscJsonString([string]$s){')
[void]$New.Add('  if ($null -eq $s) { return "" }')
[void]$New.Add('  $sb = New-Object System.Text.StringBuilder')
[void]$New.Add('  for($i=0;$i -lt $s.Length;$i++){')
[void]$New.Add('    $c = [int][char]$s[$i]')
[void]$New.Add('    switch($c){')
[void]$New.Add('      34 { [void]$sb.Append("\u0022"); continue }'))
[void]$New.Add('      92 { [void]$sb.Append("\u005c"); continue }'))
[void]$New.Add('      8  { [void]$sb.Append("\u0008"); continue }'))
[void]$New.Add('      9  { [void]$sb.Append("\u0009"); continue }'))
[void]$New.Add('      10 { [void]$sb.Append("\u000a"); continue }'))
[void]$New.Add('      12 { [void]$sb.Append("\u000c"); continue }'))
[void]$New.Add('      13 { [void]$sb.Append("\u000d"); continue }'))
[void]$New.Add('      default {'))
[void]$New.Add('        if ($c -lt 32) { [void]$sb.Append(("\u{0}" -f $c.ToString("x4"))); continue }'))
[void]$New.Add('        [void]$sb.Append([char]$c)'))
[void]$New.Add('      }'))
[void]$New.Add('    }'))
[void]$New.Add('  }'))
[void]$New.Add('  return $sb.ToString()'))
[void]$New.Add('}'))
[void]$New.Add('')
[void]$New.Add('function NL_ToCanonJson($v){')
[void]$New.Add('  if ($null -eq $v) { return "null" }')
[void]$New.Add('  if ($v -is [bool]) { return ($(if($v){"true"}else{"false"})) }')
[void]$New.Add('  if ($v -is [int] -or $v -is [long] -or $v -is [double] -or $v -is [decimal]) { return ([string]$v).ToLowerInvariant() }')
[void]$New.Add('  if ($v -is [string]) { return ("`"" + (NL_EscJsonString $v) + "`"") }')
[void]$New.Add('  # IDictionary (hashtable) MUST serialize as object with sorted keys (do NOT treat as IEnumerable)')
[void]$New.Add('  if ($v -is [System.Collections.IDictionary]) {'))
[void]$New.Add('    $keys = @(@($v.Keys)) | Sort-Object'))
[void]$New.Add('    $pairs = New-Object System.Collections.Generic.List[string]'))
[void]$New.Add('    foreach($k in $keys){ $kk=[string]$k; [void]$pairs.Add(("`"" + (NL_EscJsonString $kk) + "`":" + (NL_ToCanonJson $v[$k]))) }'))
[void]$New.Add('    return ("{" + ($pairs -join ",") + "}")'))
[void]$New.Add('  }'))
[void]$New.Add('  # IEnumerable (arrays/lists)'))
[void]$New.Add('  if ($v -is [System.Collections.IEnumerable] -and -not ($v -is [string])) {'))
[void]$New.Add('    $items = New-Object System.Collections.Generic.List[string]'))
[void]$New.Add('    foreach($it in $v){ [void]$items.Add((NL_ToCanonJson $it)) }'))
[void]$New.Add('    return ("[" + ($items -join ",") + "]")'))
[void]$New.Add('  }'))
[void]$New.Add('  # PSCustomObject / other objects -> sorted properties'))
[void]$New.Add('  $ht = @{}'))
[void]$New.Add('  foreach($p in $v.PSObject.Properties){ $ht[$p.Name] = $p.Value }'))
[void]$New.Add('  $keys2 = @(@($ht.Keys)) | Sort-Object'))
[void]$New.Add('  $pairs2 = New-Object System.Collections.Generic.List[string]'))
[void]$New.Add('  foreach($k2 in $keys2){ [void]$pairs2.Add(("`"" + (NL_EscJsonString ([string]$k2)) + "`":" + (NL_ToCanonJson $ht[$k2]))) }'))
[void]$New.Add('  return ("{" + ($pairs2 -join ",") + "}")'))
[void]$New.Add('}'))
[void]$New.Add('')
[void]$New.Add('function NL_LoadTrustBundle([string]$RepoRoot){'))
[void]$New.Add('  $p = Join-Path $RepoRoot "proofs\trust\trust_bundle.json"'))
[void]$New.Add('  $t = NL_ReadUtf8 $p'))
[void]$New.Add('  if ([string]::IsNullOrWhiteSpace($t)) { NL_Die ("missing_or_empty_trust_bundle: " + $p) }'))
[void]$New.Add('  try { return ($t | ConvertFrom-Json) } catch { NL_Die ("trust_bundle_parse_failed: " + $_.Exception.Message) }'))
[void]$New.Add('}'))
[void]$New.Add('function NL_AppendReceipt([string]$RepoRoot,[string]$kind,[string]$message,[hashtable]$extra){'))
[void]$New.Add('  $p = Join-Path $RepoRoot "proofs\receipts\neverlost.ndjson"'))
[void]$New.Add('  $evt = @{ ts=(Get-Date).ToUniversalTime().ToString("o"); kind=$kind; message=$message; extra=$extra }'))
[void]$New.Add('  $line = NL_ToCanonJson $evt'))
[void]$New.Add('  $enc = New-Object System.Text.UTF8Encoding($false)'))
[void]$New.Add('  [System.IO.File]::AppendAllText($p, ($line + "`n"), $enc)'))
[void]$New.Add('}'))
[void]$New.Add('function NL_MakeAllowedSigners([string]$RepoRoot){'))
[void]$New.Add('  $tb = NL_LoadTrustBundle $RepoRoot'))
[void]$New.Add('  $keys = @(@($tb.keys))'))
[void]$New.Add('  if ($keys.Count -lt 1) { NL_Die "trust_bundle.json has no keys[]" }'))
[void]$New.Add('  $lines = New-Object System.Collections.Generic.List[string]'))
[void]$New.Add('  foreach($k in $keys){ $principal=[string]$k.principal; $pubkey=[string]$k.pubkey; if([string]::IsNullOrWhiteSpace($principal)){ NL_Die "trust_bundle.json missing principal" } if([string]::IsNullOrWhiteSpace($pubkey)){ NL_Die "trust_bundle.json missing pubkey" } [void]$lines.Add(($principal + " " + $pubkey).Trim()) }'))
[void]$New.Add('  $out = Join-Path $RepoRoot "proofs\trust\allowed_signers"'))
[void]$New.Add('  NL_WriteUtf8NoBomLf $out (($lines | Sort-Object) -join "`n")'))
[void]$New.Add('  NL_AppendReceipt $RepoRoot "allowed_signers" ("wrote " + $out) @{ line_count=$lines.Count }'))
[void]$New.Add('  return $out'))
[void]$New.Add('}'))
Write-Utf8NoBomLf $LibPath (($New.ToArray()) -join "`n")
Parse-GateFile $LibPath
Write-Host ("PATCH_OK: fixed NL_ToCanonJson stack issue. backup=" + $bak) -ForegroundColor Green
